// <auto-generated />
namespace Zensar.Core.DBEntities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ZensarInitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ZensarInitial));
        
        string IMigrationMetadata.Id
        {
            get { return "201511061029334_ZensarInitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
